%bcond_without tests
%bcond_without weak_deps

%global __os_install_post %(echo '%{__os_install_post}' | sed -e 's!/usr/lib[^[:space:]]*/brp-python-bytecompile[[:space:]].*$!!g')
%global __provides_exclude_from ^/opt/ros/kilted/.*$
%global __requires_exclude_from ^/opt/ros/kilted/.*$

Name:           ros-kilted-launch-ros
Version:        0.28.3
Release:        1%{?dist}%{?release_suffix}
Summary:        ROS launch_ros package

License:        Apache License 2.0
Source0:        %{name}-%{version}.tar.gz

Requires:       python%{python3_pkgversion}-yaml
Requires:       python3
Requires:       ros-kilted-ament-index-python
Requires:       ros-kilted-composition-interfaces
Requires:       ros-kilted-launch
Requires:       ros-kilted-lifecycle-msgs
Requires:       ros-kilted-osrf-pycommon
Requires:       ros-kilted-rclpy
Requires:       ros-kilted-ros-workspace
BuildRequires:  python%{python3_pkgversion}-devel
BuildRequires:  ros-kilted-ros-workspace
Provides:       %{name}-devel = %{version}-%{release}
Provides:       %{name}-doc = %{version}-%{release}
Provides:       %{name}-runtime = %{version}-%{release}

%if 0%{?with_tests}
BuildRequires:  python%{python3_pkgversion}-pytest
BuildRequires:  ros-kilted-ament-copyright
BuildRequires:  ros-kilted-ament-flake8
BuildRequires:  ros-kilted-ament-pep257
BuildRequires:  ros-kilted-ament-xmllint
%endif

%description
ROS specific extensions to the launch tool.

%prep
%autosetup -p1

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kilted/setup.sh" ]; then . "/opt/ros/kilted/setup.sh"; fi
%py3_build

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kilted/setup.sh" ]; then . "/opt/ros/kilted/setup.sh"; fi
%py3_install -- --prefix "/opt/ros/kilted"

%if 0%{?with_tests}
%check
# Look for a directory with a name indicating that it contains tests
TEST_TARGET=$(ls -d * | grep -m1 "\(test\|tests\)" ||:)
if [ -n "$TEST_TARGET" ] && %__python3 -m pytest --version; then
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kilted/setup.sh" ]; then . "/opt/ros/kilted/setup.sh"; fi
%__python3 -m pytest $TEST_TARGET || echo "RPM TESTS FAILED"
else echo "RPM TESTS SKIPPED"; fi
%endif

%files
/opt/ros/kilted

%changelog
* Mon Sep 15 2025 Aditya Pande <aditya.pande@openrobotics.org> - 0.28.3-1
- Autogenerated by Bloom

* Mon Jun 23 2025 Aditya Pande <aditya.pande@openrobotics.org> - 0.28.2-1
- Autogenerated by Bloom

* Tue Apr 22 2025 Aditya Pande <aditya.pande@openrobotics.org> - 0.28.1-2
- Autogenerated by Bloom

* Fri Apr 18 2025 Aditya Pande <aditya.pande@openrobotics.org> - 0.28.1-1
- Autogenerated by Bloom

* Wed Nov 20 2024 Aditya Pande <aditya.pande@openrobotics.org> - 0.28.0-1
- Autogenerated by Bloom

* Thu Oct 03 2024 Aditya Pande <aditya.pande@openrobotics.org> - 0.27.3-1
- Autogenerated by Bloom

* Mon Jul 29 2024 Aditya Pande <aditya.pande@openrobotics.org> - 0.27.2-1
- Autogenerated by Bloom

* Mon Jun 17 2024 Aditya Pande <aditya.pande@openrobotics.org> - 0.27.1-1
- Autogenerated by Bloom

* Fri Apr 26 2024 Aditya Pande <aditya.pande@openrobotics.org> - 0.27.0-1
- Autogenerated by Bloom

* Thu Mar 28 2024 Aditya Pande <aditya.pande@openrobotics.org> - 0.26.5-1
- Autogenerated by Bloom

* Wed Mar 06 2024 Aditya Pande <aditya.pande@openrobotics.org> - 0.26.4-2
- Autogenerated by Bloom

